task0-2

diff --git a/0x0F-load_balancer/0-custom_http_response_header b/0x0F-load_balancer/0-custom_http_response_header
--- a/0x0F-load_balancer/0-custom_http_response_header
+++ b/0x0F-load_balancer/0-custom_http_response_header
@@ -1,15 +1,34 @@
 #!/usr/bin/env bash
-# configures a brand new Ubuntu machine
+# uncomment to see the script run in action
 
-sudo apt -y update
-sudo apt -y upgrade
+# colors
+green='\e[1;32m'
+yellow='\e[1;33;1;40m'
+blue='\e[1;34m'
+reset='\033[0m'
 
-# installs nginx on web server
-sudo apt-get -y install nginx
+echo -e "${blue}Running updates and checks...${reset}\n"
 
-# enable nginx firewall
+function install() {
+	command -v "$1" &> /dev/null
+
+	#shellcheck disable=SC2181
+	if [ $? -ne 0 ]; then
+		echo -e "Installing: ${yellow}$1${reset}\n"
+		sudo apt-get update -y -qq && \
+			sudo apt-get install -y "$1" -qq
+		echo -e "\n"
+	else
+		echo -e "${yellow}${1} is already installed.${reset}\n"
+	fi
+}
+
+install nginx #install nginx
+
+echo -e "${green}Finishing up.${reset}\n"
+
+# allowing nginx on firewall
 sudo ufw allow 'Nginx HTTP'
-sudo ufw enable
 
 # Give the user ownership to website files for easy editing
 if [ -d "/var/www" ]; then
@@ -28,14 +47,15 @@ for dir in /var/www/{html,error}; do
 	fi
 done
 
-# modify default pages
-echo "Hello World!" | sudo tee '/var/www/html/index.html'  > /dev/null
-echo "Not found" | sudo tee '/var/www/html/error_404.html' > /dev/null
+# creating new index
+echo "Hello World!" | sudo tee '/var/www/html/index.html' > /dev/null
+
+# create new error page
+echo "Ceci n'est pas une page" | sudo tee '/var/www/html/error_404.html' > /dev/null
 
 # backup default server config file
 sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup
 
-# setup custom header on web server
 server_config=\
 "server {
 		listen 80 default_server;
@@ -48,7 +68,7 @@ server_config=\
 			try_files \$uri \$uri/ =404;
 		}
 		if (\$request_filename ~ redirect_me){
-			rewrite ^ https://th3-gr00t.tk/ permanent;
+			rewrite ^ https://alphaziro.tech/ permanent;
 		}
 		error_page 404 /error_404.html;
 		location = /error_404.html {
@@ -57,7 +77,7 @@ server_config=\
 }"
 
 #shellcheck disable=SC2154
-echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default
+echo "$server_config" | sudo tee '/etc/nginx/sites-enabled/default' > /dev/null
 
 if [ "$(pgrep -c nginx)" -le 0 ]; then
 	sudo service nginx start
